= Taiga: Importers
:toc: left
:numbered:
:source-highlighter: pygments
:pygments-style: friendly

You can configure importers for Jira, Github and Trello in your own instance.

== Trello

For configure Trello, you have to go to https://trello.com/app-key and obtaing
your API key and your oauth secret, and then, configure it in your `settings/config.py`:

[source,python]
----
IMPORTERS["trello"] = {
    "active": True,
    "api_key": "your-trello-api-key",
    "secret_key": "your-trello-oauth-secret"
}
----

And you have to enable in your dist/conf.json in taiga-front adding it to importers list:

[source,js]
----
{
    ...
    "enableTrelloImporter": true,
    ...
}
----

== Github

To configure Github, you have to go to https://github.com/settings/developers,
register a new application and obtain a client id and a client secret. When creating
the GitHub OAuth app the "Authorization callback URL" should be set to the base url
for your Taiga instance. After you have created the app you have to configure Taiga
for it in your settings/config.py:

[source,python]
----
IMPORTERS["github"] = {
    "active": True,
    "client_id": "your-github-client-id",
    "client_secret": "your-github-client-secret"
}
----

And you have to enable in your dist/conf.json in taiga-front adding it to importers list:

[source,js]
----
{
    ...
    "enableGithubImporter": true,
    ...
}
----

== Jira

=== Important notice about Jira releases and Taiga compatibility

* Taiga support Jira releases up to 8.3.5. It has been tested and should work out of the box.
* Taiga might support Jira releases from 8.3.5 to 8.5.x. Most probably it works.
* Taiga does not support Jira releases from 8.6.

=== Configure Jira importers

For configure Jira, you have to go to generate a public of private/public keys
pair. To do this, you can run the next command:

[source,bash]
----
openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
openssl rsa -pubout -in private_key.pem -out public_key.pem
----

Once you have the public and private key, you can configure it in your
settings/config.py:

[source,python]
----
IMPORTERS["jira"] = {
    "active": True,
    "consumer_key": "one-key-at-your-election",
    "cert": open('private_key.pem').read(),  # You can directly copy and paste the content here
    "pub_cert": open('public_key.pem').read(),  # You can directly copy and paste the content here
}
----

And you have to enable in your dist/conf.json in taiga-front adding it to importers list:

[source,js]
----
{
    ...
    "enableJiraImporter": true,
    ...
}
----

After that, you have to configure your Jira instance to allow to connect using this certificates, you can get more information about it in https://resources.taiga.io/extend/importer-jira/
