Taiga documentation
===================
:toc: left
:numbered:


Introduction
------------

Your Agile, Free and Open Source Project Management Tool


Project Maturity
----------------

Because _taiga_ is still a young project we consider it is currently in beta state.


How it works
------------

Taiga is made up of two components: link:https://github.com/taigaio/taiga-front[taiga-front]
and link:https://github.com/taigaio/taiga-back[taiga-back]

- *taiga-front* has the front related code built with *angularjs* and *coffescript*.
  It can runs on any static file server like nginx.
- *taiga-back* has the backend related code consisting of an api, built using *django*
  and *python3*.

Taiga has some other modules, but they are optional and documented in other sections.

Requirements
------------

This is a list of major taiga dependencies:

Runtime:

- Python 3.4
- PostgreSQL >= 9.3
- RabbitMQ (optional if you dont want async notifications)

Compile time:

- GCC & Development Headers
- Ruby 2.1 (only for compile sass)
- NodeJS 0.10 (with npm, gulp and bower for download dependencies and compile coffeescript)


Installation Guide
------------------

This section details everythign you need to know to get taiga up and running
on both development and production environments.


Setup production environment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

link:setup-production.html[This document] contains the complete, step by step tutorial of how
to setup properly taiga for low traffic production environment.


Setup development environment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

You can see link:setup-development.html[here] the complete documentation on how to setup
a proper development environment.


Other ways to setup initial environment
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Additionally to traditional step by step manuals, taiga comes with some other tools like
collection of provisioning scripts and vagrant support, and the complete documentation
of how to use them is link:setup-alternatives.html[here].


How to contribute
-----------------

Because Taiga is an open source project, we gratefully accept contributions in various forms.

Examples of contributions include:

- Code patches.
- Improvemnent.
- Bug reports.
- Patch reviews.

Before starting to develope a big feature (intending to be included on the taiga code base), it is
strongly recommended that you reach out to us at link:http://groups.google.com/d/forum/taigaio[mailing list].

Reporting bugs
~~~~~~~~~~~~~~

Before reporting a bug or requesting a new feature, please consider these general points:

- Check that someone hasn't already filed the bug or feature request by searching our running custom queries in the ticket tracker.
- Check the right repository to use for report a issue: bugs related to UI should go to *taiga-front*, if something is broken on backend, the issue should be opened on *taiga-back* repository.
- Do ask on link:http://groups.google.com/d/forum/taigaio[mailing list] first if you're not sure if what you're seeing is a bug.
- Don't use the github issues system to ask support questions. Use the link:http://groups.google.com/d/forum/taigaio[mailing list] for that.
- Don’t use the github issues for lengthy discussions, because they're likely to get lost. If a particular ticket is controversial, please move the discussion to the link:http://groups.google.com/d/forum/taigaio[mailing list].

License
~~~~~~~

Every code patch accepted in the taiga codebase is acceoted under the AGPL v3.0 license. It is important that you
not include any code that can not be licensed under AGPL v3.0.

You can see the complete license on `LICENSE` file on the root of repository.
