= Taiga Documentation
:toc: left
:toclevels: 1

Free. Open Source. Powerful. _Taiga_ is a project management platform for startups
and agile developers & designers who want a simple, beautiful tool that makes work
truly enjoyable.

[[installation-guide]]
== Installation Guide

This section details everything you need to know to get _Taiga_ up and running in production environments.

=== Setup Production Environment with Docker [Recommended]

link:setup-production.html#setup-prod-with-docker[This document contains the complete tutorial for installation with docker] of how
to properly setup _Taiga_ for a low traffic production environment.

=== Setup Production Environment from Source Code

link:setup-production.html#setup-prod-from-source-code[This document contains the complete, step by step tutorial] of how
to properly setup _Taiga_ for a low traffic production environment.

=== Setup FAQs and common Bugs

You can view a list of common FAQs and bugs related to the setup process link:setup-faqs.html[FAQs
and common bugs].

[[upgrading-guide]]
== Upgrading Guide

This section explains how to upgrade your current Taiga to a newer version

=== Upgrade from Taiga5 to Taiga6

Update your link:upgrades-5to6.html[Taiga5 instance to a new Taiga6 version].
This section covers different upgrade scenarios:

- from Taiga5 source code to Taiga6 in docker
- from Taiga5 in docker to Taiga6 in docker
- from Taiga5 source code to Taiga6 source code

=== Older versions

Update between link:upgrades-older.html[versions].


[[how-to-contribute]]
== How to Contribute

Because _Taiga_ is an open source project, we gratefully accept contributions in various forms.

Examples of contributions include:

- link:#reporting-bugs[Bug reports]
- Code patches
- Improvements
- Patch reviews
- link:#translate[Translate]
- link:#themes[Create a theme]
- link:#contrib-plugins[Code contrib plugins]

Before starting to develop a big feature (intended to be included on the _Taiga_ code base), it is
strongly recommended that you reach out to us on the link:http://groups.google.com/d/forum/taigaio[mailing list].


[[reporting-bugs]]
=== Reporting Bugs

Before reporting a bug or requesting a new feature, please consider these general points:

- Check that someone hasn't already filed the bug or feature request by searching, or running custom
  queries in, the link:https://tree.taiga.io/project/taiga/issues[issue tracker].
- Check the right repository to use for reporting an issue: bugs related to UI should go to *taiga-front*,
  but if something is broken on the backend, an issue should be opened on the *taiga-back* repository.
- Ask on the link:http://groups.google.com/d/forum/taigaio[mailing list] first if you're not sure if
  what you're seeing is a bug.
- Don't use the GitHub issues system to ask support questions. Use the
  link:http://groups.google.com/d/forum/taigaio[mailing list] for that.
- Don’t use GitHub issues for lengthy discussions, because they're likely to get lost. If a particular
  ticket is controversial, please move the discussion to the
  link:http://groups.google.com/d/forum/taigaio[mailing list].


[[development]]
== Development

This section details everything you need to know to get _Taiga_ up and running in development environments.

=== Setup Development Environment

You can view the complete documentation on how to link:setup-development.html[setup a proper
development environment].


[[api]]
== API

_Taiga_ has a complete REST API (the one used by the web app), check the full API
documentation link:api.html[here].


[[importers]]
== Importers

_Taiga_ importers are designed to ease the migration of data from others platforms. Check the full documentation link:importers.html[here].


[[webhooks]]
== Webhooks

_Taiga_ has a webhooks notification system, check the full documentation link:webhooks.html[here].


[[integrations]]
== Integrations

You can integrate _Taiga_ with:

* link:integrations-github.html[GitHub]
* link:integrations-gitlab.html[Gitlab]
* link:integrations-bitbucket.html[Bitbucket]
* link:integrations-gogs.html[Gogs]


[[contrib-plugins]]
== Contrib Plugins

Taiga supports the inclusion of contrib plugins, each plugin has its own
documentation and repository. The currently supported plugins are:

* link:http://github.com/taigaio/taiga-contrib-github-auth[taiga-github-auth]: GitHub Auth plugin
* link:http://github.com/taigaio/taiga-contrib-hipchat[taiga-contrib-hipchat]: HipChat integration plugin
* link:http://github.com/taigaio/taiga-contrib-letschat[taiga-contrib-letschat]: Lets Chat integration plugin
* link:http://github.com/taigaio/taiga-contrib-slack[taiga-contrib-slack]: Slack integration plugin


[[community]]
== Community

link:http://groups.google.com/d/forum/taigaio[Taiga has a mailing list]. Feel free to join it
and ask any questions you may have.

To subscribe for announcements of releases, important changes and so on, please follow
link:https://twitter.com/taigaio[@taigaio] on Twitter or read our link:https://blog.taiga.io[blog].


[[license]]
== License

Every code patch accepted in the Taiga codebase is accepted under the AGPL v3.0 license. It is important
that you do not include any code which cannot be licensed under AGPL v3.0.

You can see the complete license in the `LICENSE` file in the root of the repository.
