Setup production environment
============================
:toc: left
:numbered:

Introduction
------------

This documentation explains how to deploy a taiga service (each module part of taiga platform).

The Taiga platform consists of three main components:

- **taiga-back** (backend/api)
- **taiga-front** (frontend)
- **taiga-events** (websockets gateway) (optional)

And each one has its own dependencies, at compile time and runtime.

Each component can run on one unique machine or they can each be installed in a different machine. In
this tutorial we will setup everything in one single machine. This setup should suffce should for small/medium
production environments.

Before start
------------

This tutorial assumes that you are using a clean, recently updated, **ubuntu 14.04** image.

Due the nature of frontend application, you should know that this service will be used 
through the domain/public-ip. This is because, the frontend application will run on your browser
and it should communicate with the backend/api.

We assume the following:

- **ip:** `80.88.23.45`
- **hostname:** `example.com` (which points to 80.88.23.45)
- **username:** `taiga`


Backend installation
--------------------

This section helps with the installation of the backend (api) taiga service.

Install dependencies
~~~~~~~~~~~~~~~~~~~~

The Backend is written mainly in python (3.4) but for some third party libraries we need to install a
C compiller and development headers.

[source,bash]
----
sudo apt-get install -y build-essential binutils-doc autoconf flex bison libjpeg-dev
sudo apt-get install -y libfreetype6-dev zlib1g-dev libzmq3-dev libgdbm-dev libncurses5-dev
sudo apt-get install -y automake libtool libffi-dev curl git tmux
----

Setup a database
~~~~~~~~~~~~~~~~

**taiga-back** also requires postgresql (>= 9.3) as a database

Install postgresql:

[source,bash]
----
sudo apt-get install -y postgresql-9.3 postgresql-contrib-9.3
sudo apt-get install -y postgresql-doc-9.3 postgresql-server-dev-9.3
----

And setup teh initial user and database:

[source,bash]
----
sudo -u postgres createuser taiga
sudo -u postgres createdb taiga -O taiga
----

Setup python environment
~~~~~~~~~~~~~~~~~~~~~~~~

For run **taiga-back** you should have python (3.4) installed with some other third party
libraries. As a first step, start installing python:

[source,bash]
----
sudo apt-get install -y python3 python3-pip python-dev python3-dev python-pip
----

Afterward, install **virtualenvwrapper**:

[source,bash]
----
pip3 install --user virtualenvwrapper
----

**virtualenvwrapper** helps maintain the system clean of third party libraries installed
with language package manager. Before you use virtualevwrapper, you should configure it.

Create a shell configuration file:

.~/.virtualenvwrapper-conf.sh
[source, bash]
----
export PYTHONPATH="/home/ubuntu/.local/lib/python3.4/site-packages"
export WORKON_HOME=$HOME/.virtualenvs
export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3.4"
export PATH=~/.local/bin:$PATH
source ~/.local/bin/virtualenvwrapper.sh
----

Include it from you shell configuration file, in case of ubuntu, we are using *bash* and the
configuration file is `~/.bash_profile`.

.Add this line at the end of **~/.bash_profile**
[source, bash]
----
source ~/.virtualenvwrapper-conf.sh
----

Restart your shell or execute `source ~/.virtualenvwrapper-conf.sh`.

Having virtualenvwrapper ready, you can start downloading the **taiga-base** source code from
its repository and setup all the third party libraries it requires:

.Download the code
[source,bash]
----
cd ~
git clone https://github.com/taigaio/taiga-back.git taiga-back
cd taiga-back
git checkout stable
----

.Create new virtualenv
[source,bash]
----
mkvirtualenv taiga
----

.Install dependencies
[source, bash]
----
pip install -r requirements.txt
----

.Populate the database with initial basic data
[source,bash]
----
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py loaddata initial_role
python manage.py collectstatic --noinput
----

This creates a new user **admin** with password **123123**.

If you want some example data, you can execute the following command, which populates the database
with sample projects and random data, usefull for demos:

[source,bash]
----
python manage.py sample_data
----

And as final step for setup **taiga-back**, we should create the intial configuration
for proper static/media files resolution and optionally, email sending support:

.Put this on ~/taiga-back/settings/local.py
[source,python]
----
from .common import *

MEDIA_URL = "http://example.com/media/"
STATIC_URL = "http://example.com/static/"
ADMIN_MEDIA_PREFIX = "http://example.com/static/admin/"
SITES["front"]["domain"] = "example.com"

SECRET_KEY = "theveryultratopsecretkey"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "no-reply@example.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Uncomment this if you want activate email sending
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_USE_TLS = False
# EMAIL_HOST = "localhost"
# EMAIL_HOST_USER = ""
# EMAIL_HOST_PASSWORD = ""
# EMAIL_PORT = 25
----

Verification
~~~~~~~~~~~~

To make sure everything is working, you can run the backend in development mode with:

[source,bash]
----
python manage.py runserver
----

Then you must be able to see a json representing the list of endpoints in the url http://localhost:8000/api/v1/ .


[NOTE]
Now we have backend installed and setup successful. Obviously this is not finished here, because python
in production environments should run in one application server. This details are explained on the last
section of this document.


Frontend installation
---------------------

This section helps you install the frontend application

Install dependencies
~~~~~~~~~~~~~~~~~~~~

The Frontend application runs entirelly on a browser, and it should be written using javascript, css and html.
In case of **taiga-front** we have used other languaes. Because of this, you should install some
additional dependencies that compiles **taiga-front** code intro something that the browser can understand.


Ruby and Gems
^^^^^^^^^^^^^

Ruby is used mainly for compiling *sass* (css preprocessor). It is also used for sass linting but that
is only on development environments.

.Install ruby
[source,bash]
----
sudo apt-get install -y ruby
----

.Install required gems
[source,bash]
----
gem install --user-install sass scss-lint
----

.Make gems scripts available in path putting this on *~/.bash_profile*
[source,bash]
----
export PATH=~/.gem/ruby/1.9.1/bin:$PATH
----

Restart the shell or run bash to make the path changes available.


NodeJS and friends
^^^^^^^^^^^^^^^^^^

NodeJS is used to execute **gulp** and **bower**:

- **gulp**: task execution tool. Used mainly for executing deploying and compiling tasks.
- **bower**: javascript dependencies management tool. Used mainly for downloading third party libraries
  used by **taiga-front**.

.Install nodejs
[source,bash]
----
sudo apt-get install -y nodejs npm
----

.Install **gulp** and **bower** using recently installed npm
[source,bash]
----
sudo npm install -g gulp bower
----

.Download the code
[source,bash]
----
cd ~
git clone https://github.com/taigaio/taiga-front.git taiga-front
cd taiga-front
git checkout stable
----

.Install all dependencies needed for run gulp and compile taiga-front
[source,bash]
----
npm install
bower install
----

Final steps
~~~~~~~~~~~

Having installed all dependencies, only two steps are left: creating the configuration and compiling.

.Create intial configuration on ~/taiga-front/conf/main.json
[source,json]
----
{
    "api": "http://example.com/api/v1/",
    "eventsUrl": "ws://example.com/events",
    "debug": "true",
    "publicRegisterEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null
}
----

.Run gulp task for compile
[source,bash]
----
cd ~/taiga-front
gulp deploy
----

Now, having compiled **taiga-front**, the next step is to expose the generated code
(in **dist** directory) under static file web server: we use **nginx**. That process is
explained in the last section of this tutorial.

Verification
~~~~~~~~~~~~

To make sure everything is ok, you can check the **dist** directory and you'll see an
**index.html** file and **fonts**, **images**, **js**, **partials**, **plugins**,
**styles** and **svg** directories.

Events installation
-------------------

**This step is completelly optional and can be skipped**

TODO

Final steps
-----------

If you are here, it's probable that you completed the installation of **taiga-back** and
**taiga-front**. However, having installed them is insufficient.

**taiga-back** should run under application server which in turn should be executed and monitored
by one process manager. For this task we will use **gunicorn** and **circus** respectivelly.

**taiga-front** and **taiga-back** should be exposed to the outside, using good proxy/static-file
web server. For this purpose we'll use **nginx**.


Circus and gunicorn
~~~~~~~~~~~~~~~~~~~

Circus is a process manager written by **Mozilla** and we will use it to execute **gunicorn**.
Circus not only serves to execute processes, it also has utils for monitoring them, collecting logs,
restarting processes if something goes wrong, and starting processes on system boot.

.Install circus
[source,bash]
----
sudo pip2 install circus
----

.Initial configuration for circus on ~/circus.ini
[source,ini]
----
[circus]
check_delay = 5
endpoint = tcp://127.0.0.1:5555
pubsub_endpoint = tcp://127.0.0.1:5556
statsd = true

[watcher:taiga]
working_dir = /home/taiga/taiga-back
cmd = gunicorn
args = -w 3 -t 60 --pythonpath=. -b 0.0.0.0:8001 taiga.wsgi
uid = taiga
numprocesses = 1
autostart = true
send_hup = true
stdout_stream.class = FileStream
stdout_stream.filename = /home/taiga/logs/gunicorn.stdout.log
stdout_stream.max_bytes = 10485760
stdout_stream.backup_count = 4
stderr_stream.class = FileStream
stderr_stream.filename = /home/taiga/logs/gunicorn.stderr.log
stderr_stream.max_bytes = 10485760
stderr_stream.backup_count = 4

[env:taiga]
PATH = $PATH:/home/taiga/.virtualenvs/taiga/bin
----

[NOTE]
====
We store logs on the user home, making them available and immediately accessible when
you enter a machine. To make everything work, make sure you have the logs directory
created.

You can create it with: `mkdir -p ~/logs`
====

.Setup circus for start on boot putting this on `/etc/init/circus.conf`
[source,text]
----
start on filesystem and net-device-up IFACE=lo
stop on runlevel [016]

respawn
exec /usr/local/bin/circusd /home/taiga/circus.ini
----

And finally start circus:

[source,bash]
----
sudo service circus start
----


Nginx
~~~~~

Nginx is used as a static file web server to serve **taiga-front** and send proxy requests to **taiga-back**.

Let start configuring it.

.Add specific configuration for **taiga-front** and **taiga-back** on /etc/nginx/sites-available/taiga.
[source,nginx]
----
server {
    listen 80 default_server;
    server_name _;

    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;

    access_log /home/taiga/logs/nginx.access.log;
    error_log /home/taiga/logs/nginx.error.log;

    # Frontend
    location / {
        root /home/taiga/taiga-front/dist/;
        try_files $uri $uri/ /index.html;
    }

    # Backend
    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001/api;
        proxy_redirect off;
    }

    # Static files
    location /static {
        alias /home/taiga/taiga-back/static;
    }

    # Media files
    location /media {
        alias /home/taiga/taiga-back/media;
    }
}
----

[NOTE]
====
You can configure it as a virtual host, if you want to have various webs in the same nginx.
====

.Remove the link on /etc/nginx/sites-enabled/default and add /etc/nginx/sites-enabled/taiga
[source,nginx]
----
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/taiga /etc/nginx/sites-enabled/taiga
----

And finally, restart nginx with `sudo service nginx restart`

**Now you should have the service up and running on `http://example.com/`**

FAQ
---

How I can change the domain name?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The domain name mainly affects the frontend application, because it needs to comunicate with the
backend through the domain/public-ip.

To do this you should update the `url` value on frontend config file and rebuild frontend with
`gulp deploy`. Also you should update the domain related configuration on the backend
settings file: `settings/local.py`.

And finally reload the backend config with: `circusctl reload taiga`

How can I restart backend application?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The Backend application is running under circus. To restart any application running
with circus use the `circusctl` command:

[source,bash]
----
circusctl restart taiga
----

How I can maintain my app up to date with the most recent taiga version?
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The Taiga platform is developed on github. For consistences you should alway maintain the same version
in time with the *stable* branch of git repository.

**No packaged version of taiga is available at this moment.**

.Frontend application
[source,bash]
----
cd ~/taiga-front
git pull
gulp deploy
----

.Backend application
----
cd ~/taiga-back
workon taiga
git pull
pip install --upgrade -r requirements.txt
python manage.py migrate --noinput
python manage.py collectstatic --noinput
circusctl reload taiga
----

