= Upgrade from Taiga5 to Taiga6
:toc: left
:toclevels: 1
:numbered:
:source-highlighter: pygments
:pygments-style: friendly

[[taiga5-to-taiga6dckr]]
== Recommended Upgrade Process

This is the recommended migration process, as using Taiga6 with docker is the recommended way to run Taiga in production. This tutorial assumes that you have a Taiga5 instance running either from source code or from Taiga5 docker images.

**Note** Although there are different Taiga docker images, this tutorial has been tested with:

- link:https://hub.docker.com/r/devinsolutions/taiga[devinsolutions/taiga]

- link:https://hub.docker.com/r/taigaio/taiga5[official taigaio/taiga5]

For other installations, the steps to "Get the data from Taiga5" may differ.

=== Requirements and caveats

Prior to start the migration, ensure:

* you have access to the Taiga5 server and its configuration:
** in a source code installation, a `local.py` file
** in a docker installation, the `docker-compose.yml` file
* you have access to the Taiga6 server, and have cloned the link:https://github.com/kaleidos-ventures/taiga-docker[taiga-docker] repository
* the Taiga6 server has `docker` and `docker-compose`

Besides, have in mind that:

- for this migration, you stop the access to Taiga5 service to prevent state modifications (bbdd and media files)
- this tutorial asumes that the destination bbdd is empty or may be emptied

=== Get the data from Taiga5

[WARNING]
====
Before moving on through this tutorial, this could be a perfect moment to prevent other users from changing data in Taiga5. Remove the access to Taiga5.
====

==== ... in a source code installation

.Media files
Typically media files are in `taiga-back/media`. Create a tar with all the media files:
[source,bash]
----
$ cd taiga-back/
$ tar -czf taiga5_media.tar.gz media
----

.Database dump
Create a dump with the data; with postgres, it would be:
[source,bash]
----
$ pg_dump -U $TAIGA_DB_USER -h $TAIGA_DB_HOST $TAIGA_DB_NAME > taiga5_db.sql
----

Move these two files to the server where Taiga6 will be.

==== ... in a docker installation

.Media files
Inside the container, media files are in `/srv/taiga-back/media`. To get them, enter the server container interactively and follow these steps:
[source,bash]
----
:/# cd /srv/taiga-back
:/# tar -czf media/taiga5_media.tar.gz media
----

Exit the container and get the media file:
[source,bash]
----
$ docker cp {CONTAINER_NAME}:/srv/taiga-back/media/taiga5_media.tar.gz .
----

.Database dump
Enter the database container interactively and:
[source,bash]
----
:/# cd
:/# pg_dump -U $TAIGA_DB_USER -h $TAIGA_DB_HOST $TAIGA_DB_NAME > taiga5_db.sql
----

Exit the container and get the dump file:
[source,bash]
----
$ docker cp {CONTAINER_NAME}:/taiga5_db.sql .
----

Move these two files to the server where Taiga6 will be.

[[install-taiga6]]
=== Get Taiga6

Clone link:https://github.com/kaleidos-ventures/taiga-docker[this repository] in the Taiga6 server.
[source,bash]
----
$ cd taiga-docker/
$ git checkout stable
----

=== Configuration

There are two options to migrate the configuration:

**Simple configuration**: most likely this configuration will serve to your scenario. Open `docker-compose.yml` and migrate your configuration in `local.py` to the corresponding environment variables.

**Advanced configuration**: if you have a `local.py` with some complex settings, you can ignore the environment variables and map a `config.py` file (check the `x-volumes` section in docker-compose.yml).

=== Load the old dump

Follow these steps:
[source,bash]
----
# Run only the database to avoid migrations
$ docker-compose up -d taiga-db

# Copy the dump inside the container:
$ docker cp taiga5_db.sql taiga-docker_taiga-db_1:/taiga5_db.sql

# Access the container
$ docker exec -ti taiga-docker_taiga-db_1 /bin/bash
----

And inside the container, load the dump:
[source,bash]
----
:/# psql -U taiga taiga < taiga5_db.sql
----

Check that the data have been properly migrated. Delete the taiga5_db.sql file and exit the container.

=== Migrate the database

Next step is to run Taiga6 backend so the database can be migrated to the new schema:
[source,bash]
----
$ docker-compose up -d taiga-back
----

=== Migrate the media files

With the backend up and running, copy the taiga5_media.tar.gz file inside the backend container and access the container:
[source,bash]
----
$ docker cp taiga5_media.tar.gz taiga-docker_taiga-back_1:/taiga5_media.tar.gz
$ docker exec -ti taiga-docker_taiga-back_1 /bin/bash
----

And inside the container, remove the old media and extract the files:
[source,bash]
----
:/# mv /taiga5_media.tar.gz /taiga-back/media
:/# cd /taiga-back/media
:/# tar -xzvf taiga5_media.tar.gz --strip 1
:/# rm taiga5_media.tar.gz
:/# chown -R taiga:taiga *
----

Exit the container, and continue with other configurations.

=== Other configurations

Before going on, check all the configurations recommended in the environment files.

=== Run Taiga6

Once everything has been migrated, launch all the services and check the result:

[source,bash]
----
$ docker-compose up -d
----

Go to `http://localhost:9000` where everything should be migrated and available.

=== Confingure the proxy

Your host configuration needs to make a proxy to `http://localhost:9000`. Example:

----
server {
  server_name taiga.mycompany.com;

  ...

  location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_pass http://localhost:9000/;
  }
}
----


[[taiga5src-to-taiga6src]]
== From Taiga5 source code to Taiga6 source code

This is the recommended migration if you installed Taiga5 from source code and want to keep it that way.

=== PostgreSQL

Although it's not strictly mandatory, it's highly recommended to keep PostgreSQL updated. Check the link:https://www.postgresql.org/docs/13/upgrading.html[official documentation] and choose the best way that fits your scenario.

=== RabbitMQ

Although it's not strictly mandatory, it's highly recommended to keep RabbitMQ updated. Check the link:https://www.rabbitmq.com/upgrade.html[official documentation] and choose the best way that fits your scenario.

=== Back

[WARNING]
====
Run as a non-priviledged user like `taiga`, do not run this code as `root`.
====

[source,bash]
----
# Update the code
$ cd ~/taiga-back
$ git checkout stable
$ git fetch && git reset --hard origin/stable

# Activate your virtual environment

# Update the dependencies
$ pip install -r requirements.txt
----

**Configuration** has changed the way it's used. Now, it's expected to read a DJANGO_SETTINGS_MODULE from environment with the namespace to the configuration file. Example:

[source,bash]
----
$ DJANGO_SETTINGS_MODULE=settings.local python manage.py
----

If this envvar doesn't exist, the system defaults to `settings.common`.
Besides this change in the configuration system, you should check and use the file `settings/config.py.prod.example` with all the options. We strongly recommend that you copy this file and port your `local.py` settings:

[source, bash]
----
cp settings/config.py.prod.example settings/config.py
----

Edit this file with your settings from `local.py` and check the new settings.

**Important note**: new `config.py` expects a database configuration, instead of relying in the database configuration of `common.py`. Make sure you migrate your database credentials to `config.py` file.

[WARNING]
====
Check out the new `ENABLE_TELEMETRY` setting.
====

[WARNING]
====
If you have some contrib plugins installed you should to upgrade them before the next step.
====

[source,bash]
----
$ DJANGO_SETTINGS_MODULE=settings.config python manage.py migrate --noinput
$ DJANGO_SETTINGS_MODULE=settings.config python manage.py compilemessages
$ DJANGO_SETTINGS_MODULE=settings.config python manage.py collectstatic --noinput
----

Update `/etc/systemd/system/taiga.service` to have all the options shown at link:setup-production.html#expose-taiga-back[these instructions].

Restart taiga service.

=== Async tasks

Upgrade this module always after the backend.

If you are not using the `async tasks` service, we strongly recommend you to do:
- Make sure you have `CELERY_ENABLED=True` in your `config.py` file
- Make sure you have the RabbitMQ credentials in the `config.py` file
- Create the systemd unit following link:setup-production.html#expose-taiga-async[these instructions]

If you were already using `async tasks`, then:
- update your `config.py` file with the new environment variables (check link:https://github.com/kaleidos-ventures/taiga-back/blob/stable/settings/confi.py.prod.example[the example])
- update `/etc/systemd/system/taiga-async.service` (it was called `taiga-celery.service`) to have all the options shown at link:setup-production.html#expose-taiga-async[these instructions].

Restart taiga-async service.

=== Front

[source,bash]
----
$ cd ~/taiga-front-dist
$ git checkout stable
$ git rebase && git reset --hard origin/stable
----

Restart nginx service.

=== Events

If you are not using the `events` service, we strongly recommend you to do:

- Install the service following link:setup-production.html#taiga-events[these_instructions]
- Create the systemd unit following link:setup-production.html#expose-taiga-events[these instructions]

If you were already using `events`, it's important that you update all dependencies, because they have completely changed. Configuration and systemd unit have changed as well. These are the steps to update it:

[source,bash]
----
$ cd ~/taiga-events
$ git checkout stable
$ git rebase && git reset --hard origin/stable

# Update the dependencies
$ npm install
----

Use the new config file `.env`:
[source,bash]
----
cp .env.example .env
----
Edit the file and put your own data (before it was in a `config.json` file).

Edit the systemd unit (most likely in `/etc/systemd/system/taiga-events.service`) to be like:
[source,ini]
----
[Unit]
Description=taiga_events
After=network.target

[Service]
User=taiga
WorkingDirectory=/home/taiga/taiga-events
ExecStart=npm run start:production
Restart=always
RestartSec=3

[Install]
WantedBy=default.target
----

Reload the systemd daemon and restart the `taiga-events` service:

[source,bash]
----
sudo systemctl daemon-reload
sudo systemctl restart taiga-events
----


=== Protected

If you are not using the `protected` service, we strongly recommend you to do:

- Install the service following link:setup-production.html#install-protected[these instructions]
- Add the contrib protected plugin following link:setup-production.html#add_contrib_protected[these instructions]
- Create the systemd unit following link:setup-production.html#expose-taiga-protected[these instructions]

To update it:
[source,bash]
----
$ cd ~/taiga-protected
$ git checkout stable
$ git rebase && git reset --hard origin/stable
----

**Important note**: check the configuration variables needed for this module:
[source,bash]
----
DEFAULT_FILE_STORAGE = "taiga_contrib_protected.storage.ProtectedFileSystemStorage"
THUMBNAIL_DEFAULT_STORAGE = DEFAULT_FILE_STORAGE
----

Restart the taiga-protected and taiga-back services.

=== Nginx

Although it's not strictly mandatory, it's highly recommended to keep Nginx updated. Check the link:http://nginx.org/en/docs/install.html[official documentation] and choose the best way that fits your scenario.

Besides, there is a new recommended base configuration for Nginx (slightly different from Taiga5), so we encourage you to link:setup-production.html#nginx[check it and update it].
