How to upgrade Taiga
====================
:toc: left

The Taiga platform is developed on github. For consistences you should alway maintain the same version
in time with the *stable* branch of git or use the last major version of each component.

**No packaged version of Taiga is available at this moment.**

Default upgrade process
-----------------------

Frontend application
~~~~~~~~~~~~~~~~~~~~

[source,bash]
----
cd ~/taiga-front-dist
git checkout stable
git pull
----

Backend application
~~~~~~~~~~~~~~~~~~~

[WARNING]
====
As user `taiga` or whatever user you use, do not run this code as `root` to avoid errors.
====

[source,bash]
----
cd ~/taiga-back
git checkout stable
workon taiga
git pull
pip install --upgrade -r requirements.txt
----

[WARNING]
====
If you have some contrib plugin installed you should to upgrade then before the next step.
====

[source,bash]
----
python manage.py migrate --noinput
python manage.py compilemessages
python manage.py collectstatic --noinput
circusctl reload taiga
----

In case taiga-celery is configured reload it too:

[source,bash]
----
circusctl reload taiga-celery
----

1.9.0 > 1.9.1
-------------

Copy your conf.json from `taiga-front-dist/dist/js/conf.json` to `taiga-front-dist/dist/conf.json`.

Remove the following folders `dist/fonts`, `dist/images`, `dist/js`, `dist/locales`, `dist/styles`, `dist/svg`.

Download the latest plugins version following their installation instructions.


1.9.1 > 1.10.0
--------------

Follow the default process.

The migration could take a long time if you have a large database.


1.10.0 > 2.0.0
--------------

Follow the default process.

This version upgrade Django to 1.9, so if you overwrited the DB settings in `taiga-back/settings/local.py` you have to change the DB backend to use the default one.

So, change...

[source,python]
----
# In Taiga <= 1.9
DATABASES = {
    "default": {
        "ENGINE": "transaction_hooks.backends.postgresql_psycopg2",
        (...)
----

to:

[source,python]
----
# In Taiga >= 2.0
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        (...)
----


2.0.0 > 2.1.0
--------------

Follow the default process.

2.1.0 > 3.0.0
-------------

[IMPORTANT]
.Extra step for instances with gogs plugin installed
====

Taiga contrib gogs plugin has been moved to taiga core so in case you installed the plugin you must uninstall it first:

- In `taiga-back/settings/local.py`
    * Remove `taiga_contrib_gogs` from your `INSTALLED_APPS`
    * Remove the `PROJECT_MODULES_CONFIGURATORS["gogs"]` setting added

- In `taiga-front/dist/conf.json` remove `/plugins/gogs/gogs.json` from the `contribPlugins` section
- In `taiga-front/dist/plugins` remove the folder `gogs`
====

Follow the default process.

The migration could take a long time if you have a large database: now a new permissions has been included to allow to add comments instead of use the __modify object permission__ for this purpose.

Now project templates can be sorted and a new permission has been added to allow users to add comments. The fixtures must reloaded using:

----
cd taiga-back
workon taiga
python manage.py loaddata initial_project_templates --traceback
----

3.0.0 > 3.1.0
~~~~~~~~~~~~~~

Follow the default process.

If you want to have svg thumbnails images install `cairo` library.

----
apt-get install cairo
----

Upgrade from Ubuntu 14.04 system to Ubuntu 16.04
------------------------------------------------

To upgrade from 14.04 to 16.04 you have to follow the official Ubuntu process:

[source, txt]
----
$ sudo apt-get install update-manager-core
$ sudo do-release-upgrade -p
----

Then you have to upgrade to the new postgres version maintaining the old data:
[source, txt]
----
$ sudo apt-get install -y postgresql-9.5 postgresql-contrib-9.5
$ sudo apt-get install -y postgresql-doc-9.5 postgresql-server-dev-9.5
$ sudo pg_dropcluster 9.5 main --stop
$ sudo pg_upgradecluster 9.3 main
$ sudo reboot
----

Then you have to use the circus service from ubuntu.
[source, txt]
----
$ sudo pip uninstall circus pyzmq
$ sudo apt-get install circus
$ sudo mv ~/conf/circus.ini /etc/circus/conf.d/taiga.ini
----

Rebuild your virtualenv
[source, txt]
----
$ rmvirtualenv taiga
$ mkvirtualenv taiga -p /usr/bin/python3.5
$ cd ~/taiga-back
$ pip install -r requirements.txt
----

Reboot the system
[source, txt]
----
$ sudo reboot
----


3.0.0 > 3.1.0
-------------

Follow the default process.

The migration could take a long time if you have a large database: in these release PostgreSQL > 9.4 will be the oficial recomended version because all JSON columns will be migrated to JSONB.

You should to reload the fixtures with:

----
cd taiga-back
workon taiga
python manage.py loaddata initial_project_templates --traceback
----

If you have modified your `REST_FRAMEWORK` settings, you have to care about the changes introducted in the new version:

. In `REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"]` you have care about the fact
  that `anon` and `user` scopes settings been renamed and splited into
  `anon-write`, `anon-read`, `user-write` and `user-read`.
. In `REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"]` we have added new scopes of
  throttling by default set to `None`, they are `login-fail`, `register-success`,
  `user-detail`.
. In `REST_FRAMEWORK["DEFAULT_THROTTLE_CLASSES"]` the new default throttle
  class is `taiga.base.throttling.CommonThrottle`.

We have migrated to celery 4, and splitted the configuration in two different
files, so, if you have configured any celery setting in your
`settings/local.py` you have to move them to the `settings/celery_local.py`
file. Besides, before update the workers and taiga-back, ensure that your tasks
queue is completely empty because the tasks format isn't compatible (If you
can't stop your service during de upgrade, you have to follow the instructions
given by celery creators here:
http://docs.celeryproject.org/en/latest/whatsnew-4.0.html#upgrading-from-celery-3-1).
