= Upgrade from Taiga5 to Taiga6
:toc: left
:toclevels: 1
:numbered:

[[taiga5src-to-taiga6dckr]]
== From Taiga5 source code to Taiga6 in docker

This is the recommended migration process, as using Taiga6 with docker is the recommended way to run Taiga in production.

=== Requirements and caveats

Prior to start the migration, ensure:

- you have access to the Taiga5 server and its configuration, typically in a `local.py` file
- you have access to the Taiga6 server, and have cloned the link:https://github.com/taigaio/taiga-docker[taiga-docker] repository
- the Taiga6 server has `docker` and `docker-compose`

Besides, have in mind that:

- for this migration, you should stop the Taiga5 service, or stop the access to Taiga5 service to prevent state modifications (bbdd and media files)
- this tutorial asumes that the destination bbdd is empty or may be emptied

=== Get the data from Taiga5

.Media files
Typically media files are in `taiga-back/media`. Create a tar with all the media files:
[source,bash]
----
$ tar -czf taiga5_media.tar.gz media
----

.Data base dump
Create a dump with the data; with postgres, it would be:
[source,bash]
----
$ pg_dump -U $TAIGA_DB_USER -h $TAIGA_DB_HOST $TAIGA_DB_NAME > taiga5_db.sql
----

Move these two files to the server where Taiga6 will be.

=== Get Taiga6

Clone link:https://github.com/taigaio/taiga-docker[this repository] in the Taiga6 server.

=== Configuration

There are two options to migrate the configuration:

**Simple configuration**: most likely this configuration will serve to your scenario. Open `docker-compose.yml` and migrate your configuration in `local.py` to the corresponding environment variables.

**Complex configuration**: if you have a `local.py` with some complex settings, you can ignore the environment variables and map a `config.py` file (check the `x-volumes` section in docker-compose.yml).

=== Load the old dump

Follow these steps:
[source,bash]
----
# Run only the database to avoid migrations
$ docker-compose up -d taiga-db

# Copy the dump inside the container:
$ docker cp taiga5_db.sql taiga-docker_taiga-db_1:/taiga5_db.sql

# Access the container
$ docker exec -ti taiga-docker_taiga-db_1 /bin/bash
----

And inside the container, load the dump:
[source,bash]
----
:/# psql -U taiga taiga < taiga5_db.sql
----

Check that the data have been properly migrated. Delete the taiga5_db.sql file and exit the container.

=== Migrate the database

Next step is to run Taiga6 backend so the database can be migrated to the new schema:
[source,bash]
----
$ docker-compose up -d taiga-back
----

=== Migrate the media files

With the backend up and running, copy the taiga5_media.tar.gz file inside the backend container and access the container:
[source,bash]
----
$ docker cp taiga5_media.tar.gz taiga-docker_taiga-back_1:/taiga5_media.tar.gz
$ docker exec -ti taiga-docker_taiga-back_1 /bin/bash
----

And inside the container, remove the old media and extract the files:
[source,bash]
----
:/# rm -rf /taiga-back/media
:/# mv /taiga5_media.tar.gz /taiga-back/media
:/# cd /taiga-back/media
:/# tar -xzvf taiga5_media.tar.gz --strip 1
:/# rm taiga5_media.tar.gz
:/# chown -R taiga:taiga *
----

=== Other configurations

Before going on, check all the configurations recommended in the environment files.

=== Run Taiga6

Once everything has been migrated, launch all the services and check the result:

[source,bash]
----
$ docker-compose up -d
----

Go to `http://localhost:9000` where everything should be migrated and available.

=== Confingure the proxy

Your host configuration needs to make a proxy to `http://localhost:9000`. Example:

----
server {
  server_name taiga.mycompany.com;

  ...

  location / {
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Scheme $scheme;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_redirect off;
    proxy_pass http://localhost:9000/;
  }
}
----


== From Taiga5 docker to Taiga6 docker

(TODO)

This is the recommended migration if you were using the Taiga5 docker image.

[[taiga5src-to-taiga6src]]
== From Taiga5 source code to Taiga6 source code

(TODO)

This is the recommended migration if you installed Taiga5 from source code and want to keep it that way.
