.About Taiga instance and URLs used in this document
[NOTE]
===============================
All API calls used in the documentation are refered to Taiga.io instance, so if you use another
instance remember to change the url.

For example, if you have installed Taiga on your own PC, you must perform the tests using
_http://localhost:8000/api/v1_ instead of _https://taiga.io/api/v1_.
===============================

=== Authentication
To authenticate requests an http header called "Authorization" should be added. Its format should be:

[source]
----
Authorization: Bearer ${AUTH_TOKEN}
----

This token can be received through the link:#auth-normal-login[login API]

To provide an example, the following can be used within a Bash script running on Ubuntu - customise as appropriate for your system configuration.

- Install `jq` (a command-line JSON processor):

[source,bash]
----
$ sudo apt-get install jq
----

- Bash snippet:

[source,bash]
----
#!/bin/bash
# Request username and password for connecting to Taiga
read -p "Username: " USERNAME
read -s -p "Password: " PASSWORD

# Get AUTH_TOKEN
USER_AUTH_DETAIL=$( curl -X POST \
  -H "Content-Type: application/json" \
  -d '{
          "type": "normal",
          "username": "'${USERNAME}'",
          "password": "'${PASSWORD}'"
      }' \
  https://api.taiga.io/api/v1/auth 2>/dev/null )

AUTH_TOKEN=$( echo ${USER_AUTH_DETAIL} | jq -r '.auth_token' )

# Exit if AUTH_TOKEN is not available
if [ -z ${AUTH_TOKEN} ]; then
    echo "Error: Incorrect username and/or password supplied"
    exit 1
else
    echo "auth_token is ${AUTH_TOKEN}"
fi

# Proceed to use API calls as desired
...
----

- If unable to install `jq`, it is possible (but not recommended) to use `grep` and `cut` to extract the value of `auth_token` from the JSON link:#object-auth-user-detail[user auth detail object] - use the following line instead:

[source,bash]
----
AUTH_TOKEN=$( echo ${USER_AUTH_DETAIL} | grep -Po '"auth_token":.*?[^\\]",' | cut -d\" -f4 )
----

=== OCC - Optimistic concurrency control
In taiga multiple operations can be happening at the same time for an element so every modifying request should include a valid version parameter. You can think about two different users updating the same user story, there are two possible scenarios here:

- They are updating the same attributes on the element. In this situation the API will accept the first request and deny the second one because the version parameter will be considered as invalid.
- They are updating different attributes on the element. In this situation the API is smart enough for accepting both requests, the second one would have an invalid version but the changes are not affecting modified attributes so they can be applied safely

The version parameter is considered valid if it contains the current version for the element, it will be incremented automatically if the modification is successful.

=== Pagination
By default the API will always return paginated results and includes the following headers in the response:

- x-paginated: boolean indicating if pagination is being used for the request
- x-paginated-by: number of results per page
- x-pagination-count: total number of results
- x-pagination-current: current page
- x-pagination-next: next results
- x-pagination-prev: previous results

*Disabling pagination* can be accomplished by setting an extra http header:

[source]
----
x-disable-pagination: True
----

=== Internationalization
The API returns some content translated, you can specify the language with an extra http header:

[source]
----
Accept-Language: {LanguageId}
----

The LanguageId can be chosen from the value list of available languages. You can get them using the link:#locales[locales API].


=== Throttling

If the api is configured with throttling you have to take care on responses
with 429 (Too many requests) status code, that mean you reach the throttling
limit.
